//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication3.ReutersWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.rfa.thomsonreuters.com/", ConfigurationName="ReutersWS.ConsultaPreciosWS")]
    public interface ConsultaPreciosWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.rfa.thomsonreuters.com/ConsultaPreciosWS/obtenerPreciosRequest", ReplyAction="http://ws.rfa.thomsonreuters.com/ConsultaPreciosWS/obtenerPreciosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApplication3.ReutersWS.obtenerPreciosResponse obtenerPrecios(ConsoleApplication3.ReutersWS.obtenerPreciosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.rfa.thomsonreuters.com/ConsultaPreciosWS/obtenerPreciosRequest", ReplyAction="http://ws.rfa.thomsonreuters.com/ConsultaPreciosWS/obtenerPreciosResponse")]
        System.Threading.Tasks.Task<ConsoleApplication3.ReutersWS.obtenerPreciosResponse> obtenerPreciosAsync(ConsoleApplication3.ReutersWS.obtenerPreciosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.rfa.thomsonreuters.com/")]
    public partial class campos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rICField;
        
        private campo[] fLDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string RIC {
            get {
                return this.rICField;
            }
            set {
                this.rICField = value;
                this.RaisePropertyChanged("RIC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FLD", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public campo[] FLD {
            get {
                return this.fLDField;
            }
            set {
                this.fLDField = value;
                this.RaisePropertyChanged("FLD");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.rfa.thomsonreuters.com/")]
    public partial class campo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fLDField;
        
        private string vALField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FLD {
            get {
                return this.fLDField;
            }
            set {
                this.fLDField = value;
                this.RaisePropertyChanged("FLD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string VAL {
            get {
                return this.vALField;
            }
            set {
                this.vALField = value;
                this.RaisePropertyChanged("VAL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPrecios", WrapperNamespace="http://ws.rfa.thomsonreuters.com/", IsWrapped=true)]
    public partial class obtenerPreciosRequest {
        
        public obtenerPreciosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPreciosResponse", WrapperNamespace="http://ws.rfa.thomsonreuters.com/", IsWrapped=true)]
    public partial class obtenerPreciosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rfa.thomsonreuters.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PRICE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ConsoleApplication3.ReutersWS.campos[] @return;
        
        public obtenerPreciosResponse() {
        }
        
        public obtenerPreciosResponse(ConsoleApplication3.ReutersWS.campos[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultaPreciosWSChannel : ConsoleApplication3.ReutersWS.ConsultaPreciosWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaPreciosWSClient : System.ServiceModel.ClientBase<ConsoleApplication3.ReutersWS.ConsultaPreciosWS>, ConsoleApplication3.ReutersWS.ConsultaPreciosWS {
        
        public ConsultaPreciosWSClient() {
        }
        
        public ConsultaPreciosWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaPreciosWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaPreciosWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaPreciosWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication3.ReutersWS.obtenerPreciosResponse ConsoleApplication3.ReutersWS.ConsultaPreciosWS.obtenerPrecios(ConsoleApplication3.ReutersWS.obtenerPreciosRequest request) {
            return base.Channel.obtenerPrecios(request);
        }
        
        public ConsoleApplication3.ReutersWS.campos[] obtenerPrecios() {
            ConsoleApplication3.ReutersWS.obtenerPreciosRequest inValue = new ConsoleApplication3.ReutersWS.obtenerPreciosRequest();
            ConsoleApplication3.ReutersWS.obtenerPreciosResponse retVal = ((ConsoleApplication3.ReutersWS.ConsultaPreciosWS)(this)).obtenerPrecios(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication3.ReutersWS.obtenerPreciosResponse> ConsoleApplication3.ReutersWS.ConsultaPreciosWS.obtenerPreciosAsync(ConsoleApplication3.ReutersWS.obtenerPreciosRequest request) {
            return base.Channel.obtenerPreciosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication3.ReutersWS.obtenerPreciosResponse> obtenerPreciosAsync() {
            ConsoleApplication3.ReutersWS.obtenerPreciosRequest inValue = new ConsoleApplication3.ReutersWS.obtenerPreciosRequest();
            return ((ConsoleApplication3.ReutersWS.ConsultaPreciosWS)(this)).obtenerPreciosAsync(inValue);
        }
    }
}
