	SELECT 

		CONVERT(VARCHAR(10),A.dtedate,112)AS FECHA,
		UPPER([txtTv]) AS TIPO_VALOR ,
		UPPER([txtEmisora]) AS EMISORA,
		UPPER([txtSerie]) AS SERIE,
		LTRIM( CONVERT(VARCHAR(400),STR(ROUND([dblPRL],6),15,6))) AS PRECIO_LIMPIO,
		
		LTRIM( STR(ROUND([dblPRS],6),15,6)) AS PRECIO_SUCIO,
		LTRIM( STR(ROUND([dblCPD],6),10,6)) AS INTERECES_ACUMULADOS,
		LTRIM( STR(ROUND([dblCPA],6),10,6)) AS CUPON_ACTUAL,
		LTRIM( STR(ROUND([dblLDR],6),10,6)) AS SOBRE_TASA,
		RTRIM(LTRIM([txtNEM]))AS NOMBRE_COMPLETO,--10
		RTRIM(LTRIM([txtSEC]))AS SECTOR,
		RTRIM(LTRIM([txtMOE]))AS MONTO_EMITIDO,
		RTRIM(LTRIM([txtMOC]))AS MONTO_EN_CIRCULACION,
		
		RTRIM(CASE WHEN txtISD = '-' OR txtISD = 'NA' THEN 'NA' ELSE CONVERT(CHAR(10),CONVERT(DATETIME, ISNULL(txtISD, '1900-01-01')),112) END )AS FECHA_EMISION,
		
		RTRIM(LTRIM([txtTTM])) AS PLAZO_EMISION,
		
		RTRIM(CASE WHEN txtMTD = '-' OR txtMTD = 'NA' THEN 'NA' 
		ELSE CONVERT(CHAR(10),CONVERT(DATETIME, ISNULL(txtMTD, '1900-01-01')),112) END)AS FECHA_VCTO,
		
		
		CASE WHEN txtNOM = '-' OR txtNOM = 'NA' THEN 'NA' ELSE STR(ROUND(RTRIM(LTRIM([txtNOM])),12),21,12)END AS VALOR_NOMINAL,
		
		UPPER(RTRIM(LTRIM([txtCUR])))AS MONEDA_EMISION,
		
		UPPER(RTRIM(LTRIM([txtIRCSUBY])))AS SUBYACENTE,
		CASE WHEN  txtCYT = '-' OR txtCYT = 'NA' THEN 'NA' ELSE  STR(ROUND(RTRIM(LTRIM([txtCYT])),6),10,6)END AS REND_COLOCACION ,--20
		
		CASE WHEN txtOSP = '-' OR txtOSP ='NA' THEN 'NA' ELSE  STR(ROUND(RTRIM(LTRIM([txtOSP])),6),10,6)END AS ST_COLOCACION,
		UPPER(RTRIM(LTRIM([txtCPF])))AS FREC_CPN,
		[dblCPA]AS TASA_CUPON,--<<<>>>
		RTRIM(LTRIM([txtDTC]))AS DIAS_TRANSC_CPN,
		UPPER(RTRIM(LTRIM([txtCRL])))AS DIAS_TRANSC_CPN,
		RTRIM(LTRIM([txtTCR]))AS CUPONES_EMISION,
		RTRIM(LTRIM([txtFCR])) AS CUPONES_X_COBRAR,

		CASE WHEN txtLPV = '-' OR txtLPV = 'NA' THEN 'NA' ELSE 
		CASE ISNUMERIC(txtLPV) WHEN 1 THEN   LTRIM(STR(ROUND(RTRIM(LTRIM([txtLPV])),6),15,6)) else 'NA' END END AS HECHO_DE_MKT,
			
		CASE WHEN txtLPD = '-' OR txtLPD = 'NA' THEN 'NA' ELSE 
			CASE  WHEN txtLPD NOT IN('NA') THEN   CONVERT(CHAR(10),CONVERT(DATETIME, ISNULL(txtLPD, '1900-01-01')),112)  else 'NA' END END AS FECHA_UH, 
		CASE WHEN txtTHP = '-' OR txtTHP = 'NA' THEN 'NA' ELSE 
				CASE ISNUMERIC(txtTHP) WHEN 1 THEN   LTRIM(STR(ROUND(RTRIM(LTRIM([txtTHP])),6),15,6)) else 'NA' END END AS PRECIO_TEORICO, --30
			
		CASE WHEN txtLCA = '-' OR txtLCA = 'NA' THEN 'NA' ELSE 
			CASE ISNUMERIC(txtLCA) WHEN 1 THEN   LTRIM(STR(ROUND(RTRIM(LTRIM([txtLCA])),6),10,6)) else 'NA' END END AS POST_COMPRA,
			

		CASE WHEN txtLPU = '-' OR txtLPU = 'NA' THEN 'NA' ELSE 
				CASE ISNUMERIC(txtLPU) WHEN 1 THEN   LTRIM(STR(ROUND(RTRIM(LTRIM([txtLPU])),6),10,6)) else 'NA' END END AS POST_VENTA,
			
		CASE WHEN txtBYT = '-' OR txtBYT = 'NA' THEN 'NA' ELSE 
				CASE ISNUMERIC(txtBYT) WHEN 1 THEN   LTRIM(STR(ROUND(RTRIM(LTRIM([txtBYT])),6),10,6)) else 'NA' END END  AS YIELD_COMPRA,--txtBYT AS originalBYT,
			
		CASE WHEN txtOYT = '-' OR txtOYT = 'NA' THEN 'NA' ELSE 
				CASE ISNUMERIC(txtOYT) WHEN 1 THEN   LTRIM(STR(ROUND(LTRIM([txtOYT]),6),10,6)) else 'NA' END END AS YIELD_VENTA,--txtOYT AS ORIGINALOYT,
				
				
			
		CASE WHEN txtBSP = '-' OR txtBSP = 'NA' THEN 'NA' ELSE 
				CASE ISNUMERIC(txtBSP) WHEN 1 THEN   LTRIM(STR(ROUND(RTRIM(LTRIM([txtBSP])),6),10,6)) else 'NA' END END AS SPREAD_COMPRA,
			
		CASE WHEN txtPSP = '-' OR txtPSP = 'NA' THEN 'NA' ELSE 
				CASE ISNUMERIC(txtPSP) WHEN 1 THEN   LTRIM(STR(ROUND(RTRIM(LTRIM([txtPSP])),6),10,6)) else 'NA' END END AS SPREAD_VENTA,
		
		RTRIM(LTRIM([txtDPQ])) AS MDYS,
		RTRIM(LTRIM([txtSPQ])) AS S_P,
		UPPER(RTRIM(LTRIM([txtBUR])))AS BURSATILIDAD,
		RTRIM(LTRIM(a.txtLIQ))AS LIQUIDEZ,--40
		RTRIM(LTRIM([txtDPC]))AS CAMBIO_DIARIO,
		RTRIM(LTRIM([txtWPC]))AS CAMBIO_SEMANAL,
		
		CASE WHEN txtMHP = '-' OR txtMHP = 'NA' THEN 'NA' ELSE 
				CASE ISNUMERIC(txtMHP) WHEN 1 THEN   LTRIM(STR(ROUND(RTRIM(LTRIM([txtMHP])),6),15,6)) else 'NA' END END AS PRECIO_MAX_12M,--BR_PRC_MA2 
				
		CASE WHEN txtIHP = '-' OR txtIHP = 'NA' THEN 'NA' ELSE 
				CASE ISNUMERIC(txtIHP) WHEN 1 THEN   LTRIM(STR(ROUND(RTRIM(LTRIM([txtIHP])),6),15,6)) else 'NA' END END AS PRECIO_MAX_12M ,--BR_PRC_MI2
		RTRIM(LTRIM([txtSUS])) AS SUSPENSION,

		RTRIM(LTRIM([txtVOL])) AS VOLATILIDAD,
		RTRIM(LTRIM([txtVO2]))AS VOLATILIDAD_2,
		
		CASE WHEN txtDMF = '-' OR txtDMF = 'NA' THEN 'NA' ELSE 
			CASE ISNUMERIC(txtDMF) WHEN 1 THEN   LTRIM(STR(ROUND(RTRIM(LTRIM([txtDMF])),12),20,12)) else 'NA' END END AS DURACION,
				
		CASE WHEN txtDMT = '-' OR txtDMT = 'NA' THEN 'NA' ELSE 
			CASE ISNUMERIC(txtDMT) WHEN 1 THEN  LTRIM(STR(ROUND(RTRIM(LTRIM([txtDMT])),12),20,12)) else 'NA' END END AS DURACION_MONET,
		----
		CASE WHEN txtCMT = '-' OR txtCMT = 'NA' THEN 'NA' ELSE 
			CASE ISNUMERIC(txtCMT) WHEN 1 THEN  LTRIM(STR(ROUND(RTRIM(LTRIM([txtCMT])),12),19,12)) else 'NA' END END AS CONVEXIDAD,--50
			
		CASE WHEN txtVAR = '-' OR txtVAR = 'NA' THEN 'NA' ELSE 
			CASE ISNUMERIC(txtVAR) WHEN 1 THEN  LTRIM(STR(ROUND(RTRIM(LTRIM([txtVAR])),12),19,12)) else 'NA' END END AS VAR_,
			
			RTRIM(LTRIM([txtSTD]))AS ESVIACION_STAND,
			
		CASE WHEN txtVNA = '-' OR txtVNA = 'NA' THEN 'NA' ELSE 
			CASE ISNUMERIC(txtVNA) WHEN 1 THEN  LTRIM(STR(ROUND(RTRIM(LTRIM([txtVNA])),6),13,6)) else 'NA' END END AS VALOR_NOMINAL_ACTUALIZADO,
		
		RTRIM(LTRIM([txtFIQ])) AS CALIFICACION_FITCH,


		CASE WHEN txtDMH = '-' OR txtDMH = 'NA' THEN 'NA' ELSE 
			CASE  when txtDMH NOT IN ('NA') THEN   LTRIM(CONVERT(CHAR(10),CONVERT(DATETIME, ISNULL(txtDMH, '1900-01-01')),112)) ELSE 'NA' END END AS FECHA_PRECIO_MAXIMO, 
				
		 
		 
		 
		CASE WHEN txtDIH = '-' OR txtDIH = 'NA' THEN 'NA' ELSE 
			CASE when txtDIH NOT IN ('NA') THEN   LTRIM(CONVERT(CHAR(10),CONVERT(DATETIME, ISNULL(txtDIH, '1900-01-01')),112)) else 'NA' END END AS FECHA_PRECIO_MINIMO,
				 
 		 
 	
 		 
		CASE WHEN txtSTP = '-' OR txtSTP = 'NA' THEN 'NA' ELSE 
			CASE ISNUMERIC(txtSTP) WHEN 1 THEN   LTRIM(STR(ROUND(RTRIM(LTRIM([txtSTP])),12),20,12)) else 'NA' END END AS SENSIBILIDAD,
			
			
		CASE WHEN txtDMC = '-' OR txtDMC = 'NA' THEN 'NA' ELSE 
			CASE ISNUMERIC(txtDMC) WHEN 1 THEN  LTRIM(STR(ROUND(RTRIM(LTRIM([txtDMC])),12),20,12)) else 'NA' END END AS DURACION_MACAULAY,
			
		RTRIM(LTRIM([dblYTM]))AS TASA_DE_RENDIMIENTO,--<<<>>>
		
		RTRIM(LTRIM([txtHRQ]))AS HR_RATINGS,--60	
		
		RTRIM( CASE WHEN txtDEF = '-' OR txtDEF = 'NA' THEN 'NA' ELSE 
			CASE ISNUMERIC(txtDEF) WHEN 1 THEN  LTRIM(RTRIM(LTRIM(STR(ROUND([txtDEF],12),20,12)))) else 'NA' END END )AS  DURACION_EFECTIVA,
			